// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAokxQPTA0XvOJIMAOdyNvK6IQWhxjdDpo',
    appId: '1:1071853428448:web:d99143e84e87f377fc7a85',
    messagingSenderId: '1071853428448',
    projectId: 'mahd-b6c1b',
    authDomain: 'mahd-b6c1b.firebaseapp.com',
    storageBucket: 'mahd-b6c1b.firebasestorage.app',
    measurementId: 'G-HSDTMTRR6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOfNQfiArVz4dfqnxA1V4d6_teb4qEtSA',
    appId: '1:1071853428448:android:1f39d1981c36b6fffc7a85',
    messagingSenderId: '1071853428448',
    projectId: 'mahd-b6c1b',
    storageBucket: 'mahd-b6c1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAVIcTOSWBAeoVpQCOGizG6SGECfiyY7k',
    appId: '1:1071853428448:ios:d801f779cea01cd6fc7a85',
    messagingSenderId: '1071853428448',
    projectId: 'mahd-b6c1b',
    storageBucket: 'mahd-b6c1b.firebasestorage.app',
    iosClientId: '1071853428448-3gki0muhojt494v89cph0qda1uukcl5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.napd',
  );
}
