import 'package:dio/dio.dart';

class ApiInterceptor extends Interceptor {
  String token =
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNyIsImVtYWlsIjoiYWRtaW4zQGdtYWlsLmNvbSIsImp0aSI6IjdlNjJlMGRkLTBjMDItNDA2NS1iMmE1LTE2ZmYzMWZkOTU3ZiIsImV4cCI6MTc0ODAwNzIyMiwiaXNzIjoiTWFNYUNhcmUiLCJhdWQiOiJNYU1hQ2FyZSJ9.PMJpQWQI-0K7NL6JNZ9VU1fFNBweYOO2hv6jJzNfwGQ';
  @override
  void onRequest(RequestOptions options, RequestInterceptorHandler handler) {
    options.headers['Accept-Language'] = 'en';
    options.headers['Authorization'] = 'Bearer $token';
    options.headers['Cookie'] =
        '.AspNetCore.Identity.Application=CfDJ8Dym9pq823RPiaQw-D9e4YaR6bHoif_dzoVtzFDCITOuDXM6K8YmXVNm3hEy1JIQ1Kdudky3CRExUxpdu614INctLmFwmN0FVSOq-sd5gHU_xFDubwi5Tjr16AqmSUzqG-SJbVJWVDffkWr3giKS7MxpEQ2n1nkmnFJ_Go3W2ODUPOm6gxmFlsW71Y8CTldBsvFZdFiUlJ7qnN6W0o8vNSNHjPNF19CCUd24h09RPKJaZIrE365L3l7oRr3mwop2XBTSF9un6loEnZOTSDdty_LtCFaMgVJynqg9sDRcTqyekq_bM5x-SwYSV5hy_R59pLdMVac7_gebUZkWo3SSGlpFAvXw3kAWzMJu13Hzb0FS7nKTRKChOm2DKfnhHxRSDJypu5BBGaXbJ84egyluASfZiOmeWHZRasDwZleuSiTVSfS_4jYAsvyeGWjjye8OmKnqOpcQW8zuvEINdjaEBebfhxESJw6s-C12QEU6i4njQHtm-RJ4o4gFcyQmN09F6pjisAWgAbtpj8jLYZlq26Hh48xRi0nGamhTOXecKQaM3sa94L8ooaSXau1HPG_Xf602wQafEJ0LNdNPSejvCRZ1qOsXEuzHXEu_xQFUX5_aLKYPD-dRPVMe3gV_uCTPTFUpXAJJjatbSKAVen4y7W_6IkqB6jnwiX0ngGfJUtfejFV_s97YQWdPIKoKG5gjlw';
    super.onRequest(options, handler);
  }
}
